spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0 # Assign a random port
